# Generated by Django 6.0.5 on 2026-05-27 10:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_options_chat_name_and_more'),
    ]

    operations = [
    ]
