# Generated by Django 6.0.5 on 2026-05-27 10:58

import chat.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_options_chat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=chat.fields.ChatNameField(blank=True, default='chat', max_length=255),
            preserve_default=False,
        ),
    ]
