# Generated by Django 6.0.5 on 2026-05-27 11:52

import core
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_chat_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="related_id",
            field=core.fields.RelatedIDField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
