services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    env_file:
      - .env
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A studai worker --loglevel=info
    volumes:
      - .:/app/
    env_file:
      - .env
    depends_on:
      - redis
  redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"